[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.optimized"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environment]
PORT = "8080"
NODE_ENV = "production"